# Generated by Django 4.1.5 on 2023-03-01 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_user"),
        ("shopping_cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcarrito",
            name="color",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.color",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemcarrito",
            name="talla",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.talla",
            ),
            preserve_default=False,
        ),
    ]
