# Generated by Django 4.1.5 on 2023-02-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="desc",
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
