# Generated by Django 4.1.5 on 2023-02-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cantidad",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
