# Generated by Django 4.1.5 on 2023-02-12 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_cantidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="product",
            field=models.ManyToManyField(
                through="products.Color_product", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="talla",
            name="product",
            field=models.ManyToManyField(
                through="products.Talla_product", to="products.product"
            ),
        ),
        migrations.AlterField(
            model_name="talla_product",
            name="talla",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.talla"
            ),
        ),
    ]
