# Generated by Django 4.1.5 on 2023-02-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_color_product_talla_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="photos"),
        ),
    ]
